name: React App

on:
  push:
  workflow_dispatch:

jobs:
  build-test-react-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.9'
      - name: Install Python requirements
        run: pip install -r requirements.txt
      - name: Copy file to staging
        run: |
          mkdir -p staging
          cp *.py staging/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: python-project 
          path: staging
        
